sudo: false  # Not needing sudo enables container builds.

addons:
  apt:
    sources:
    - sourceline: 'deb [arch=amd64] http://storage.googleapis.com/bazel-apt stable jdk1.8'
      key_url: 'https://bazel.build/bazel-release.pub.gpg'
    - sourceline: 'ppa:hvr/ghc'
    packages:
    - bazel
    - ghc-8.2.1

before_script:
  - export PATH=/opt/ghc/bin:$PATH

script:
  - bazel test //...
